
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infodb
    username: infouser
    password: infopass
#  mvc:
#    throw-exception-if-no-handler-found: true

doma:
  dialect: mysql
  query-timeout: 60
  sql-file-repository: no_cache

