version: "3"
services:
  db:
    Image: mysql:5.7
    container_name: infodb
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8
    volumes:
      - ./cnf:/etc/mysql/conf.d
      - ./initdb:/docker-entrypoint-initdb.db
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306